spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  application:
    name: dubbo-provider

  dubbo:
    scan:
       basePackages: com.example.demodubboprovider.service
    server: true
    registry: zookeeper://127.0.0.1:2181
    protocol:
       name: dubbo
       port: 20881

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch: DEBUG